# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- testbuild

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'

steps:
  - task: DotNetCoreCLI@2
    displayName: 'Restore'
    inputs:
      command: 'restore'
      projects: '**/Kros.Utils.csproj'

  - task: DotNetCoreCLI@2
    displayName: 'Build'
    inputs: 
      command: 'build'
      projects: '**/Kros.Utils.csproj'
      arguments: --configuration $(BuildConfiguration)

# - script: 
#     dotnet restore
#     dotnet build --configuration $(buildConfiguration)
#   displayName: 'dotnet build $(buildConfiguration)'
