# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- testbuild

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'

steps:
  - task: DotNetCoreCLI@2
    displayName: 'Restore'
    inputs:
      command: 'restore'
      projects: '**/Kros.Utils.csproj'

  - task: DotNetCoreCLI@2
    displayName: 'Build'
    inputs: 
      command: 'build'
      projects: '**/Kros.Utils.csproj'
      arguments: --configuration $(BuildConfiguration) --no-restore

  - task: VSTest@2
    displayName: 'Tests'
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: '**\Kros.Utils.UnitTests.dll!'
