trigger:
  batch: true
  tags:
    include:
    - v*.*

pool:
  vmImage: 'windows-2019'

variables:
  - group: Nuget
  - name: buildConfiguration
    value: 'Release'

steps:
  - task: DotNetCoreCLI@2
    displayName: 'Restore'
    inputs:
      command: 'restore'
      projects: '**/Kros.Utils.csproj'

  - task: DotNetCoreCLI@2
    displayName: 'Build'
    inputs:
      command: 'build'
      projects: '**/Kros.Utils.csproj'
      arguments: --configuration $(BuildConfiguration) --no-restore

  - task: DotNetCoreCLI@2
    displayName: 'Tests'
    inputs:
      command: test
      projects: '**/Kros.Utils.UnitTests.csproj'

  - task: NuGetCommand@2
    inputs:
      command: pack
      packagesToPack: '**/Kros.Utils.csproj'

  - task: NuGetCommand@2
    inputs:
      command: push
      nuGetFeedType: external
      publishFeedCredentials: $(nuget.feed)
