trigger:
  batch: true
  tags:
    include:
    - v*

pool:
  vmImage: ubuntu-latest

variables:
  - group: Nuget

steps:
  - pwsh: |
      Get-ChildItem -Path '$(Build.ArtifactStagingDirectory)' -Recurse -Include *.nupkg, *.snupkg | Remove-Item
      Get-ChildItem -Path '$(Build.SourcesDirectory)' -Recurse -Include *.nupkg, *.snupkg | Remove-Item
    displayName: Clear NuGet packages

  - template: build-and-test.yml

  - task: CopyFiles@2
    displayName: Copy package files to staging directory
    inputs:
      Contents: |
        **/*.nupkg
        **/*.snupkg
      TargetFolder: $(build.artifactStagingDirectory)
      FlattenFolders: true

  - pwsh: |
      dotnet nuget push --api-key $(nugetOrgApiKey) --source 'https://api.nuget.org/v3/index.json' '$(Build.ArtifactStagingDirectory)/*.nupkg'
    displayName: Push to NuGet.org
