trigger:
  batch: true
  branches:
    include:
    - master

pool: 'default'

variables:
  - group: Nuget
  - name: buildConfiguration
    value: 'Release'
  - name: projectName
    value: 'Kros.Utils'

steps:
  - task: DotNetCoreCLI@2
    displayName: 'Nuget restore'
    inputs:
      command: 'restore'
      projects: '**/$(projectName).csproj'

  - task: DotNetCoreCLI@2
    displayName: 'Build'
    inputs:
      command: build
      projects: '**/$(projectName).csproj'
      arguments: '--configuration $(BuildConfiguration) --no-restore'

  - task: DotNetCoreCLI@2
    displayName: 'Tests'
    inputs:
      command: test
      projects: '**/$(projectName).UnitTests.csproj'
